camunda.client.mode=saas
camunda.client.auth.client-id=7pT~nH4Xag1Bbt52NSkFyMoaiGburR0I
camunda.client.auth.client-secret=df0_NM2CV.rxBjzSi0U8t78tp__ZRQFXomJ-5Id05jMHfKa5Jekd0vO-ofBW6YAi
camunda.client.cloud.cluster-id=860b5191-17d8-45ab-8392-4c05dd12c7ff
camunda.client.cloud.region=cdg-1

#
#spring.datasource.url=jdbc:mysql://localhost:3306/priya
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Drivergit

spring.datasource.url=jdbc:mysql://localhost:3306/title_insurence
spring.datasource.username=root
spring.datasource.password=Venu@143
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl.auto=update
spring.jpa.show-sql=true


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#camunda.client.prefer-rest-over-grpc=true
#camunda.client.worker.defaults.stream-enabled=false
#camunda.client.request-timeout=PT2M
#camunda.client.worker.defaults.request-timeout=PT2M

server.port=8080

