camunda.client.mode=saas
camunda.client.auth.client-id=7pT~nH4Xag1Bbt52NSkFyMoaiGburR0I
camunda.client.auth.client-secret=df0_NM2CV.rxBjzSi0U8t78tp__ZRQFXomJ-5Id05jMHfKa5Jekd0vO-ofBW6YAi
camunda.client.cloud.cluster-id=860b5191-17d8-45ab-8392-4c05dd12c7ff
camunda.client.cloud.region=cdg-1
